---
# tasks file for dns

- name: Stop resolvconf
  service:
    name: resolvconf
    state: stopped
  tags:
    - setup
    - dns

- name: Remove resolvconf
  package:
    name: resolvconf
    state: absent
  tags:
    - setup
    - dns

- name: Create resolv.conf
  template:
    src: "{{ item }}"
    dest: "/etc/{{ item | basename | replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ dns_config_files }}"
  tags:
    - setup
    - dns
